;
; Media playlist used to validate MusicOnHold without external executables.
; Replace or extend these entries with locally licensed music as needed.
;

[en75xx-test]
mode = playlist
entry = /usr/share/asterisk/sounds/demo-congrats
entry = /usr/share/asterisk/sounds/demo-thanks
